# Generated by Django 5.1.1 on 2024-09-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tafseer', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
    ]
