# Generated by Django 5.1.1 on 2024-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafseer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='معرف المستخدم')),
                ('token', models.CharField(max_length=120, verbose_name='Token')),
                ('isUsed', models.BooleanField(default=True, verbose_name='مستخدم')),
                ('payment_status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
            ],
        ),
    ]
